# Generated by Django 5.2.14 on 2026-05-25 05:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP_FLAT_FILE', 'SAP Flat File'), ('UTILITY_CSV', 'Utility Portal CSV'), ('TRAVEL_CSV', 'Corporate Travel CSV')], max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('fiscal_year_start_month', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('raw_file', models.FileField(blank=True, null=True, upload_to='raw_uploads/')),
                ('row_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='records.datasource')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='datasource',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_sources', to='records.organization'),
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_row_ref', models.CharField(blank=True, max_length=255)),
                ('raw_data', models.JSONField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('parse_error', models.TextField(blank=True)),
                ('ingestion_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_records', to='records.ingestionrun')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('split_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('scope', models.PositiveSmallIntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('category', models.CharField(choices=[('FUEL_STATIONARY', 'Fuel — Stationary Combustion'), ('FUEL_MOBILE', 'Fuel — Mobile Combustion'), ('ELECTRICITY', 'Purchased Electricity'), ('HEAT_STEAM', 'Purchased Heat/Steam'), ('BUSINESS_TRAVEL', 'Business Travel'), ('PROCUREMENT', 'Purchased Goods & Services'), ('FREIGHT', 'Upstream Transportation')], max_length=32)),
                ('activity_value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('activity_unit', models.CharField(max_length=32)),
                ('original_value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('original_unit', models.CharField(max_length=32)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('facility', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged'), ('LOCKED', 'Locked for Audit')], default='PENDING', max_length=16)),
                ('flag_reason', models.TextField(blank=True)),
                ('is_manually_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('edit_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_records', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emission_records', to='records.organization')),
                ('raw_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emission_records', to='records.rawrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('FLAG', 'Flagged'), ('UNFLAG', 'Unflagged'), ('LOCK', 'Locked for Audit'), ('COMMENT', 'Comment Added')], max_length=16)),
                ('note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_decisions', to='records.emissionrecord')),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='records.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('RECORD_CREATED', 'Record Created'), ('RECORD_EDITED', 'Record Edited'), ('RECORD_APPROVED', 'Record Approved'), ('RECORD_LOCKED', 'Record Locked'), ('INGESTION_STARTED', 'Ingestion Started'), ('INGESTION_DONE', 'Ingestion Completed'), ('FLAG_AUTO', 'Automatic Flag Raised')], max_length=32)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('target_type', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'created_at'], name='records_aud_organiz_cefa16_idx'), models.Index(fields=['target_id'], name='records_aud_target__cc8a1a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['ingestion_run'], name='records_raw_ingesti_9c08df_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organization', 'status'], name='records_emi_organiz_091c68_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organization', 'scope', 'period_start'], name='records_emi_organiz_a48e13_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organization', 'category'], name='records_emi_organiz_fcd853_idx'),
        ),
        migrations.AddConstraint(
            model_name='emissionrecord',
            constraint=models.UniqueConstraint(fields=('raw_record', 'split_index'), name='unique_emission_per_raw_split'),
        ),
    ]
